# This file was auto-generated by Fern from our API Definition.

from .generic_payment_method_customization_request import GenericPaymentMethodCustomizationRequest
import typing_extensions
from ...core.serialization import FieldMetadata
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class CustomPaymentMethodCustomizationRequest(GenericPaymentMethodCustomizationRequest):
    schema_id: typing_extensions.Annotated[str, FieldMetadata(alias="schemaId")] = pydantic.Field()
    """
    The ID of the schema to use for this payment method.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
