# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing_extensions
from .ocr_job_id import OcrJobId
from ...core.serialization import FieldMetadata
from .ocr_job_status import OcrJobStatus
import typing
from .ocr_response import OcrResponse
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class OcrJobResponse(UniversalBaseModel):
    job_id: typing_extensions.Annotated[OcrJobId, FieldMetadata(alias="jobId")]
    status: OcrJobStatus
    data: typing.Optional[OcrResponse] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
