# This file was auto-generated by Fern from our API Definition.

from .generic_payment_rail_response import GenericPaymentRailResponse
import typing_extensions
import typing
from ...invoice_types.types.bank_delivery_method import BankDeliveryMethod
from ...core.serialization import FieldMetadata
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class BankPaymentRailResponse(GenericPaymentRailResponse):
    available_delivery_methods: typing_extensions.Annotated[
        typing.List[BankDeliveryMethod], FieldMetadata(alias="availableDeliveryMethods")
    ]
    default_delivery_method: typing_extensions.Annotated[
        BankDeliveryMethod, FieldMetadata(alias="defaultDeliveryMethod")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
