# This file was auto-generated by Fern from our API Definition.

from .common_onboarding_options_request import CommonOnboardingOptionsRequest
import typing_extensions
import typing
from .onboarding_option_request import OnboardingOptionRequest
from ...core.serialization import FieldMetadata
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class IndividualOnboardingOptionsRequest(CommonOnboardingOptionsRequest):
    date_of_birth: typing_extensions.Annotated[
        typing.Optional[OnboardingOptionRequest], FieldMetadata(alias="dateOfBirth")
    ] = None
    ssn: typing.Optional[OnboardingOptionRequest] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
