# This file was auto-generated by Fern from our API Definition.

from .common_onboarding_options_response import CommonOnboardingOptionsResponse
import typing_extensions
from .onboarding_option_response import OnboardingOptionResponse
from ...core.serialization import FieldMetadata
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class IndividualOnboardingOptionsResponse(CommonOnboardingOptionsResponse):
    date_of_birth: typing_extensions.Annotated[OnboardingOptionResponse, FieldMetadata(alias="dateOfBirth")]
    ssn: OnboardingOptionResponse

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
