# This file was auto-generated by Fern from our API Definition.

import typing

PaymentGatewayError = typing.Union[
    typing.Literal[
        "NO_VALID_PAYMENT_GATEWAY_FOUND",
        "PAYMENT_GATEWAY_UNSUPPORTED",
        "CARD_DETAILS_INVALID",
    ],
    typing.Any,
]
