# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing_extensions
from ...core.serialization import FieldMetadata
import pydantic
from ...commons.types.country_code import CountryCode
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class ProcessPaymentGatewayCardDetailsDirect(UniversalBaseModel):
    """
    Examples
    --------
    from mercoa.payment_gateway_types import ProcessPaymentGatewayCardDetailsDirect

    ProcessPaymentGatewayCardDetailsDirect(
        name_on_card="John Doe",
        card_number="4242424242424242",
        expiration_month=10,
        expiration_year=2025,
        cvv="123",
        postal_code="12345",
        country="US",
    )
    """

    name_on_card: typing_extensions.Annotated[str, FieldMetadata(alias="nameOnCard")] = pydantic.Field()
    """
    The name on the card to use for the payment
    """

    card_number: typing_extensions.Annotated[str, FieldMetadata(alias="cardNumber")] = pydantic.Field()
    """
    The number of the card to use for the payment
    """

    expiration_month: typing_extensions.Annotated[int, FieldMetadata(alias="expirationMonth")] = pydantic.Field()
    """
    The month of the expiration date of the card to use for the payment. This must be a number between 1 and 12.
    """

    expiration_year: typing_extensions.Annotated[int, FieldMetadata(alias="expirationYear")] = pydantic.Field()
    """
    The year of the expiration date of the card to use for the payment. This must be the full year, not the last two digits.
    """

    cvv: str = pydantic.Field()
    """
    The CVV of the card to use for the payment
    """

    postal_code: typing_extensions.Annotated[str, FieldMetadata(alias="postalCode")] = pydantic.Field()
    """
    The postal code of the address of the card to use for the payment
    """

    country: CountryCode = pydantic.Field()
    """
    The country of the address of the card to use for the payment
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
