# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing_extensions
from .process_payment_gateway_card_details import ProcessPaymentGatewayCardDetails
from ...core.serialization import FieldMetadata
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class ProcessPaymentGatewayRequestHtml(UniversalBaseModel):
    """
    Examples
    --------
    from mercoa.payment_gateway_types import (
        ProcessPaymentGatewayCardDetails_Direct,
        ProcessPaymentGatewayRequestHtml,
    )

    ProcessPaymentGatewayRequestHtml(
        html='<html><body><h1>Invoice Details</h1><a href="https://www.payment-gateway.com/invoice/123123">Pay Invoice</a></body></html>',
        card_details=ProcessPaymentGatewayCardDetails_Direct(
            first_name="John",
            last_name="Doe",
            card_number="4242424242424242",
            expiration_month=10,
            expiration_year=2025,
            cvv="123",
            postal_code="12345",
            country="US",
            card_type="debit",
        ),
    )
    """

    html: str = pydantic.Field()
    """
    The HTML from an email to extract the payment gateway from
    """

    card_details: typing_extensions.Annotated[ProcessPaymentGatewayCardDetails, FieldMetadata(alias="cardDetails")] = (
        pydantic.Field()
    )
    """
    The details of the card to use for the payment
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
