# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing_extensions
from ...core.serialization import FieldMetadata
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class ProcessPaymentGatewayCardDetailsIframe(UniversalBaseModel):
    """
    Examples
    --------
    from mercoa.payment_gateway_types import ProcessPaymentGatewayCardDetailsIframe

    ProcessPaymentGatewayCardDetailsIframe(
        iframe_url="https://www.myvirtualcard.com/iframe/345345",
    )
    """

    iframe_url: typing_extensions.Annotated[str, FieldMetadata(alias="iframeUrl")] = pydantic.Field()
    """
    The URL of the iframe that render the virtual card details
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
