# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing_extensions
from ...core.serialization import FieldMetadata
import pydantic
from .payment_gateway_error import PaymentGatewayError
import typing
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class ProcessPaymentGatewayFailedResponse(UniversalBaseModel):
    job_id: typing_extensions.Annotated[str, FieldMetadata(alias="jobId")] = pydantic.Field()
    """
    The job ID of the payment gateway processing job
    """

    error_type: typing_extensions.Annotated[PaymentGatewayError, FieldMetadata(alias="errorType")] = pydantic.Field()
    """
    The error that occurred during the payment gateway processing job
    """

    error_message: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="errorMessage")] = (
        pydantic.Field(default=None)
    )
    """
    The error message that occurred during the payment gateway processing job
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
