# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations
from ...core.pydantic_utilities import UniversalBaseModel
import typing
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ValidatePaymentGatewayRequest_Document(UniversalBaseModel):
    """
    Examples
    --------
    from mercoa.payment_gateway_types import ValidatePaymentGatewayRequest_Document

    ValidatePaymentGatewayRequest_Document(
        document="ValidatePaymentGatewayRequestDocument.Default",
    )
    """

    type: typing.Literal["document"] = "document"
    document: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ValidatePaymentGatewayRequest_Html(UniversalBaseModel):
    """
    Examples
    --------
    from mercoa.payment_gateway_types import ValidatePaymentGatewayRequest_Document

    ValidatePaymentGatewayRequest_Document(
        document="ValidatePaymentGatewayRequestDocument.Default",
    )
    """

    type: typing.Literal["html"] = "html"
    html: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


"""
from mercoa.payment_gateway_types import ValidatePaymentGatewayRequest_Document

ValidatePaymentGatewayRequest_Document(
    document="ValidatePaymentGatewayRequestDocument.Default",
)
"""
ValidatePaymentGatewayRequest = typing.Union[ValidatePaymentGatewayRequest_Document, ValidatePaymentGatewayRequest_Html]
