# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations
from ...core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from ...core.serialization import FieldMetadata
import datetime as dt
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic
from .validate_payment_gateway_card_response import ValidatePaymentGatewayCardResponse
from .payment_gateway_error import PaymentGatewayError


class ValidatePaymentGatewayResponse_Pending(UniversalBaseModel):
    """
    Examples
    --------
    import datetime

    from mercoa.payment_gateway_types import ValidatePaymentGatewayResponse_Pending

    ValidatePaymentGatewayResponse_Pending(
        job_id="pgv_8f86116b-3b4d-4ded-99ef-3bc929d8c33c",
        created_at=datetime.datetime.fromisoformat(
            "2024-01-01 00:00:00+00:00",
        ),
        updated_at=datetime.datetime.fromisoformat(
            "2024-01-01 00:00:00+00:00",
        ),
    )
    """

    job_status: typing_extensions.Annotated[typing.Literal["pending"], FieldMetadata(alias="jobStatus")] = "pending"
    job_id: typing_extensions.Annotated[str, FieldMetadata(alias="jobId")]
    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")]
    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ValidatePaymentGatewayResponse_Success(UniversalBaseModel):
    """
    Examples
    --------
    import datetime

    from mercoa.payment_gateway_types import ValidatePaymentGatewayResponse_Pending

    ValidatePaymentGatewayResponse_Pending(
        job_id="pgv_8f86116b-3b4d-4ded-99ef-3bc929d8c33c",
        created_at=datetime.datetime.fromisoformat(
            "2024-01-01 00:00:00+00:00",
        ),
        updated_at=datetime.datetime.fromisoformat(
            "2024-01-01 00:00:00+00:00",
        ),
    )
    """

    job_status: typing_extensions.Annotated[typing.Literal["success"], FieldMetadata(alias="jobStatus")] = "success"
    job_id: typing_extensions.Annotated[str, FieldMetadata(alias="jobId")]
    payment_gateway_url: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="paymentGatewayUrl")] = (
        None
    )
    session_url: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="sessionUrl")] = None
    card: typing.Optional[ValidatePaymentGatewayCardResponse] = None
    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")]
    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ValidatePaymentGatewayResponse_Failed(UniversalBaseModel):
    """
    Examples
    --------
    import datetime

    from mercoa.payment_gateway_types import ValidatePaymentGatewayResponse_Pending

    ValidatePaymentGatewayResponse_Pending(
        job_id="pgv_8f86116b-3b4d-4ded-99ef-3bc929d8c33c",
        created_at=datetime.datetime.fromisoformat(
            "2024-01-01 00:00:00+00:00",
        ),
        updated_at=datetime.datetime.fromisoformat(
            "2024-01-01 00:00:00+00:00",
        ),
    )
    """

    job_status: typing_extensions.Annotated[typing.Literal["failed"], FieldMetadata(alias="jobStatus")] = "failed"
    job_id: typing_extensions.Annotated[str, FieldMetadata(alias="jobId")]
    error_type: typing_extensions.Annotated[PaymentGatewayError, FieldMetadata(alias="errorType")]
    error_message: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="errorMessage")] = None
    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")]
    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


"""
import datetime

from mercoa.payment_gateway_types import ValidatePaymentGatewayResponse_Pending

ValidatePaymentGatewayResponse_Pending(
    job_id="pgv_8f86116b-3b4d-4ded-99ef-3bc929d8c33c",
    created_at=datetime.datetime.fromisoformat(
        "2024-01-01 00:00:00+00:00",
    ),
    updated_at=datetime.datetime.fromisoformat(
        "2024-01-01 00:00:00+00:00",
    ),
)
"""
ValidatePaymentGatewayResponse = typing.Union[
    ValidatePaymentGatewayResponse_Pending,
    ValidatePaymentGatewayResponse_Success,
    ValidatePaymentGatewayResponse_Failed,
]
