# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .bulk_invoice_approval_from_object_response import (
    BulkInvoiceApprovalFromObjectResponse,
)
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class BulkInvoiceApprovalResponse(UniversalBaseModel):
    """
    Examples
    --------
    from mercoa.invoice_types import (
        BulkInvoiceApprovalFromObjectResponse,
        BulkInvoiceApprovalResponse,
    )

    BulkInvoiceApprovalResponse(
        data=[
            BulkInvoiceApprovalFromObjectResponse(
                id="in_26e7b5d3-a739-4b23-9ad9-6aaa085f47a9",
            ),
            BulkInvoiceApprovalFromObjectResponse(
                id="in_26e7b5d3-a739-4b23-9ad9-6aaa085f47a9",
                error="Invoice approval failed",
            ),
        ],
    )
    """

    data: typing.List[BulkInvoiceApprovalFromObjectResponse]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
