# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from ...core.serialization import FieldMetadata
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class CustomPaymentDestinationOptions(UniversalBaseModel):
    """
    Examples
    --------
    from mercoa.invoice_types import CustomPaymentDestinationOptions

    CustomPaymentDestinationOptions(
        dynamic_urls={
            "paymentLink": "https://example.com/payment-link",
            "confirmationUrl": "https://example.com/confirm",
        },
    )
    """

    dynamic_urls: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, str]], FieldMetadata(alias="dynamicUrls")
    ] = pydantic.Field(default=None)
    """
    Map of field names to dynamic URL values that will be used for dynamicUrl fields in custom payment method schemas
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
