# This file was auto-generated by Fern from our API Definition.

from ..core.client_wrapper import SyncClientWrapper
from .process.client import ProcessClient
from .validate.client import ValidateClient
from ..core.client_wrapper import AsyncClientWrapper
from .process.client import AsyncProcessClient
from .validate.client import AsyncValidateClient


class PaymentGatewayClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.process = ProcessClient(client_wrapper=self._client_wrapper)
        self.validate = ValidateClient(client_wrapper=self._client_wrapper)


class AsyncPaymentGatewayClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.process = AsyncProcessClient(client_wrapper=self._client_wrapper)
        self.validate = AsyncValidateClient(client_wrapper=self._client_wrapper)
